<?php
// Auto-generated by rebuild - 2026-08-03 02:23:16

// --- _override_es_ES.lang.php ---
// created: 2026-07-30 18:58:08
$mod_strings['LBL_PROGRAMA_INTERES'] = 'Programa de Posgrado';
$mod_strings['LBL_MEDIO_CONTACTO_C'] = 'Medio de contacto';
$mod_strings['LBL_CONTADOR_INSISTENCIAS'] = 'Número de Insistencias';
$mod_strings['LBL_EDITVIEW_PANEL1'] = 'Información de Admisiones UNL';
$mod_strings['LBL_EDITVIEW_PANEL2'] = 'undefined 2';
$mod_strings['LBL_EDITVIEW_PANEL3'] = 'Información de Admisiones UNL';

