<?php
// Auto-generated by rebuild - 2026-08-03 02:23:16

// --- _override_es_ES.lang.php ---
// created: 2026-07-31 00:22:13
$mod_strings['LBL_NUMERO_DOCUMENTO'] = 'Número de Documento';
$mod_strings['LBL_PROGRAMA_INTERES'] = 'Programa de Interés';
$mod_strings['LBL_CANAL_CAPTACION'] = 'Canal de Captación';
$mod_strings['LBL_SCORE_ASPIRANTE'] = 'Score del Aspirante ';


// --- es_ES.maestria_interesada_c.php ---
$mod_strings['LBL_MAESTRIA_INTERESADA'] = 'Maestría de Interés';
