<?php
// created: 2026-07-27 06:42:34
$sugar_config = array (
  'addAjaxBannedModules' => 
  array (
    0 => 'SecurityGroups',
  ),
  'admin_access_control' => false,
  'admin_export_only' => false,
  'allow_latest_revision_delete' => false,
  'allowed_preview' => 
  array (
    0 => 'gif',
    1 => 'png',
    2 => 'jpeg',
    3 => 'jpg',
  ),
  'anti_malware_scanners' => 
  array (
    'SuiteCRM\\Utility\\AntiMalware\\Providers\\ClamTCP' => 
    array (
      'name' => 'ClamAntiVirus TCP',
      'support_page' => 'https://www.clamav.net/',
      'enabled' => false,
      'path' => NULL,
      'options' => 
      array (
        'ip' => '127.0.0.1',
        'port' => 3310,
        'type' => 'local',
      ),
    ),
    'SuiteCRM\\Utility\\AntiMalware\\Providers\\Sophos' => 
    array (
      'name' => 'Sophos Anti Virus (Linux)',
      'support_page' => 'https://www.sophos.com/en-us/products/free-tools/sophos-antivirus-for-linux.aspx',
      'enabled' => false,
      'path' => '/opt/sophos-av/bin/savscan',
      'options' => '-ss',
    ),
  ),
  'aop' => 
  array (
    'distribution_method' => 'roundRobin',
    'case_closure_email_template_id' => 'bcd79b13-cea0-45bb-920b-2b57ba527cdc',
    'joomla_account_creation_email_template_id' => 'de8aeab4-12da-43f9-a2c6-fdcc5e22495d',
    'case_creation_email_template_id' => 'd9114a93-fcfd-4d4b-acd0-640ad24bcb2f',
    'contact_email_template_id' => '4ddb4f4e-711a-4e11-affb-fb09c046aa93',
    'user_email_template_id' => '238b39ad-1dd8-4fc5-b642-45d61ad1d424',
  ),
  'aos' => 
  array (
    'version' => '5.3.3',
    'contracts' => 
    array (
      'renewalReminderPeriod' => '14',
    ),
    'lineItems' => 
    array (
      'totalTax' => false,
      'enableGroups' => true,
    ),
    'invoices' => 
    array (
      'initialNumber' => '1',
    ),
    'quotes' => 
    array (
      'initialNumber' => '1',
    ),
  ),
  'cache_dir' => 'cache/',
  'calculate_response_time' => true,
  'calendar' => 
  array (
    'default_view' => 'week',
    'show_calls_by_default' => true,
    'show_tasks_by_default' => true,
    'show_completed_by_default' => true,
    'editview_width' => 990,
    'editview_height' => 485,
    'day_timestep' => 15,
    'week_timestep' => 30,
    'items_draggable' => true,
    'items_resizable' => true,
    'enable_repeat' => true,
    'max_repeat_count' => 1000,
  ),
  'campaign_emails_max_retries_default' => 3,
  'campaign_emails_per_run_default' => 50,
  'campaign_emails_threshold_default' => 10,
  'campaign_marketing_items_per_run_default' => 3,
  'chartEngine' => 'Jit',
  'common_ml_dir' => '',
  'create_default_user' => false,
  'cron' => 
  array (
    'max_cron_jobs' => 10,
    'max_cron_runtime' => 30,
    'min_cron_interval' => 30,
  ),
  'dashlet_auto_refresh_min' => 30,
  'dashlet_display_row_options' => 
  array (
    0 => '1',
    1 => '3',
    2 => '5',
    3 => '10',
  ),
  'date_formats' => 
  array (
    'Y-m-d' => '2010-12-23',
    'm-d-Y' => '12-23-2010',
    'd-m-Y' => '23-12-2010',
    'Y/m/d' => '2010/12/23',
    'm/d/Y' => '12/23/2010',
    'd/m/Y' => '23/12/2010',
    'Y.m.d' => '2010.12.23',
    'd.m.Y' => '23.12.2010',
    'm.d.Y' => '12.23.2010',
  ),
  'datef' => 'm/d/Y',
  'dbconfig' => 
  array (
    'db_host_name' => '127.0.0.1',
    'db_host_instance' => '',
    'db_user_name' => 'root',
    'db_password' => 'root',
    'db_name' => 'suitecrm8',
    'db_type' => 'mysql',
    'db_port' => '3306',
    'db_manager' => 'MysqliManager',
    'collation' => NULL,
    'charset' => NULL,
  ),
  'dbconfigoption' => 
  array (
    'persistent' => true,
    'autofree' => false,
    'debug' => 0,
    'ssl' => false,
  ),
  'default_action' => 'index',
  'default_charset' => NULL,
  'default_currency_iso4217' => 'USD',
  'default_currency_name' => 'US Dollar',
  'default_currency_significant_digits' => '2',
  'default_currency_symbol' => '$',
  'default_date_format' => 'Y-m-d',
  'default_decimal_seperator' => '.',
  'default_email_charset' => 'UTF-8',
  'default_email_client' => 'sugar',
  'default_email_editor' => 'html',
  'default_export_charset' => 'ISO-8859-1',
  'default_language' => 'en_us',
  'default_locale_name_format' => 's f l',
  'default_max_tabs' => 8,
  'default_module' => 'Home',
  'default_module_access' => 
  array (
    'SecurityGroups' => false,
    'AOW_WorkFlow' => false,
  ),
  'default_module_favicon' => false,
  'default_navigation_paradigm' => 'm',
  'default_number_grouping_seperator' => ',',
  'default_password' => '',
  'default_permissions' => 
  array (
    'dir_mode' => 1528,
    'file_mode' => 493,
    'user' => '',
    'group' => '',
  ),
  'default_subpanel_links' => false,
  'default_subpanel_tabs' => true,
  'default_swap_last_viewed' => false,
  'default_swap_shortcuts' => false,
  'default_theme' => 'suite8',
  'default_time_format' => 'H:i',
  'default_user_is_admin' => false,
  'default_user_name' => '',
  'demoData' => 'no',
  'developerMode' => false,
  'disableAjaxUI' => true,
  'disable_convert_lead' => false,
  'disable_export' => false,
  'disable_persistent_connections' => false,
  'display_email_template_variable_chooser' => false,
  'display_inbound_email_buttons' => false,
  'dump_slow_queries' => false,
  'email_address_separator' => ',',
  'email_calendar_invite_type' => 'rsvp_ics',
  'email_confirm_opt_in_email_template_id' => 'c5d0d7cd-3a3b-472f-902f-7095f8fa9822',
  'email_default_client' => 'sugar',
  'email_default_delete_attachments' => true,
  'email_default_editor' => 'html',
  'email_enable_auto_send_opt_in' => false,
  'email_enable_confirm_opt_in' => 'not-opt-in',
  'email_import_fetch_unread_only' => false,
  'email_import_per_run_threshold' => 25,
  'email_import_timeframe_start' => '-30 days',
  'email_warning_notifications' => false,
  'enable_action_menu' => true,
  'enable_line_editing_detail' => true,
  'enable_line_editing_list' => true,
  'enable_record_pagination' => true,
  'export_delimiter' => ',',
  'export_excel_compatible' => false,
  'external_trusted_hosts' => 
  array (
  ),
  'filter_module_fields' => 
  array (
    'Users' => 
    array (
      0 => 'show_on_employees',
      1 => 'portal_only',
      2 => 'is_group',
      3 => 'system_generated_password',
      4 => 'external_auth_only',
      5 => 'sugar_login',
      6 => 'authenticate_id',
      7 => 'pwd_last_changed',
      8 => 'is_admin',
      9 => 'user_name',
      10 => 'user_hash',
      11 => 'password',
      12 => 'last_login',
      13 => 'oauth_tokens',
    ),
    'Employees' => 
    array (
      0 => 'show_on_employees',
      1 => 'portal_only',
      2 => 'is_group',
      3 => 'system_generated_password',
      4 => 'external_auth_only',
      5 => 'sugar_login',
      6 => 'authenticate_id',
      7 => 'pwd_last_changed',
      8 => 'is_admin',
      9 => 'user_name',
      10 => 'user_hash',
      11 => 'password',
      12 => 'last_login',
      13 => 'oauth_tokens',
    ),
  ),
  'google_auth_json' => '',
  'hide_subpanels' => true,
  'history_max_viewed' => 50,
  'host_name' => 'localhost',
  'id_validation_pattern' => '/^[a-zA-Z0-9_-]*$/i',
  'image_field_height_default' => '150px',
  'image_field_listview_height_default' => '60px',
  'image_field_listview_width_default' => '100%',
  'image_field_subpanel_height_default' => '60px',
  'image_field_subpanel_width_default' => '100%',
  'image_thumbnail_height_default' => 50,
  'image_thumbnail_width_default' => 50,
  'imap_test' => false,
  'import_max_execution_time' => 3600,
  'import_max_records_per_file' => 100,
  'import_max_records_total_limit' => '',
  'installed' => true,
  'installer_locked' => true,
  'jobs' => 
  array (
    'min_retry_interval' => 30,
    'max_retries' => 5,
    'timeout' => 86400,
  ),
  'js_custom_version' => 1,
  'js_lang_version' => 1,
  'languages' => 
  array (
    'en_us' => 'English (US)',
    'es_ES' => 'Español (España) - es_ES',
  ),
  'large_scale_test' => false,
  'lead_conv_activity_opt' => 'donothing',
  'legacy_email_behaviour' => false,
  'list_max_entries_per_modal' => 10,
  'list_max_entries_per_page' => 20,
  'list_max_entries_per_subpanel' => 10,
  'listview_max_height' => 0,
  'listview_pagination_type' => 'pagination',
  'lock_default_user_name' => false,
  'lock_homepage' => false,
  'lock_subpanels' => false,
  'log_dir' => '../../logs/legacy',
  'log_file' => 'suitecrm.log',
  'log_memory_usage' => false,
  'logger' => 
  array (
    'level' => 'fatal',
    'file' => 
    array (
      'ext' => '.log',
      'name' => 'suitecrm',
      'dateFormat' => '%c',
      'maxSize' => '10MB',
      'maxLogs' => 10,
      'suffix' => '',
    ),
  ),
  'login_language' => true,
  'max_dashlets_homepage' => '15',
  'max_migration_items_to_process_per_run' => 20,
  'max_migration_items_to_queue_per_run' => 50,
  'max_processes_items_to_process_per_run' => 20,
  'max_processes_items_to_queue_per_run' => 50,
  'max_temp_file_batch_per_table' => '50',
  'max_temp_file_lifetime' => '72 hour',
  'name_formats' => 
  array (
    's f l' => 's f l',
    'f l' => 'f l',
    's l' => 's l',
    'l, s f' => 'l, s f',
    'l, f' => 'l, f',
    's l, f' => 's l, f',
    'l s f' => 'l s f',
    'l f s' => 'l f s',
  ),
  'oauth2_encryption_key' => 'R7ubzwR2Hwr/ECRm5OzqP2/vogGHzSOhLvsxz51VvKA=',
  'oauth_code_delete_threshold' => '-7 days',
  'oauth_token_delete_threshold' => '-7 days',
  'passwordsetting' => 
  array (
    'SystemGeneratedPasswordON' => '',
    'generatepasswordtmpl' => '5a9904bf-27ab-4ac8-a316-8ed7929e22c0',
    'lostpasswordtmpl' => '6b284195-a122-4063-a08b-ebef3b6b3556',
    'factoremailtmpl' => '531ff396-76e8-44d6-9947-18912099656b',
    'forgotpasswordON' => false,
    'linkexpiration' => '1',
    'linkexpirationtime' => '30',
    'linkexpirationtype' => '1',
    'systexpiration' => '1',
    'systexpirationtime' => '7',
    'systexpirationtype' => '1',
    'systexpirationlogin' => '',
  ),
  'pdf' => 
  array (
    'defaultEngine' => 'TCPDFEngine',
  ),
  'portal_view' => 'single_user',
  'record_modal_pagination_type' => 'pagination',
  'require_accounts' => true,
  'resource_management' => 
  array (
    'special_query_limit' => 50000,
    'special_query_modules' => 
    array (
      0 => 'AOR_Reports',
      1 => 'Export',
      2 => 'Import',
      3 => 'Administration',
      4 => 'Sync',
    ),
    'default_limit' => 20000,
  ),
  'rss_cache_time' => '10800',
  'save_query' => 'all',
  'search' => 
  array (
    'controller' => 'UnifiedSearch',
    'defaultEngine' => 'BasicSearchEngine',
    'pagination' => 
    array (
      'min' => 10,
      'max' => 50,
      'step' => 10,
    ),
    'ElasticSearch' => 
    array (
      'enabled' => false,
      'host' => 'localhost',
      'user' => '',
      'pass' => '',
      'index' => '0dec204a4d7d5a9cc74da3c3aa6bd600',
      'search_wildcard_char' => '%',
      'search_wildcard_infront' => true,
    ),
  ),
  'search_wildcard_char' => '%',
  'search_wildcard_infront' => false,
  'securitysuite_additive' => true,
  'securitysuite_filter_user_list' => false,
  'securitysuite_inherit_assigned' => true,
  'securitysuite_inherit_creator' => true,
  'securitysuite_inherit_parent' => true,
  'securitysuite_popup_select' => false,
  'securitysuite_strict_rights' => false,
  'securitysuite_user_popup' => true,
  'securitysuite_user_role_precedence' => true,
  'securitysuite_version' => '6.5.17',
  'session_dir' => '',
  'session_gc' => 
  array (
    'enable' => true,
    'gc_probability' => 1,
    'gc_divisor' => 100,
  ),
  'showDetailData' => true,
  'showThemePicker' => true,
  'site_url' => 'http://localhost:8000',
  'slow_query_time_msec' => '100',
  'snooze_alert_timer' => 600,
  'stackTrace' => false,
  'stack_trace_errors' => false,
  'strict_id_validation' => false,
  'subpanel_max_height' => 620,
  'subpanel_pagination_type' => 'pagination',
  'sugar_version' => NULL,
  'sugarbeet' => false,
  'suitecrm_version' => NULL,
  'system_email_templates' => 
  array (
    'confirm_opt_in_template_id' => 'c5d0d7cd-3a3b-472f-902f-7095f8fa9822',
  ),
  'system_name' => 'SuiteCRM',
  'test_email_limit' => 50,
  'time_formats' => 
  array (
    'H:i' => '23:00',
    'h:ia' => '11:00pm',
    'h:iA' => '11:00PM',
    'h:i a' => '11:00 pm',
    'h:i A' => '11:00 PM',
    'H.i' => '23.00',
    'h.ia' => '11.00pm',
    'h.iA' => '11.00PM',
    'h.i a' => '11.00 pm',
    'h.i A' => '11.00 PM',
  ),
  'timef' => 'H:i',
  'tmp_dir' => 'cache/xml/',
  'tracker_max_display_length' => 15,
  'trackers_enabled' => true,
  'translation_string_prefix' => false,
  'trusted_hosts' => 
  array (
  ),
  'unique_key' => '0dec204a4d7d5a9cc74da3c3aa6bd600',
  'upload_badext' => 
  array (
    0 => 'php',
    1 => 'php3',
    2 => 'php4',
    3 => 'php5',
    4 => 'php6',
    5 => 'php7',
    6 => 'php8',
    7 => 'pl',
    8 => 'cgi',
    9 => 'py',
    10 => 'asp',
    11 => 'cfm',
    12 => 'js',
    13 => 'vbs',
    14 => 'html',
    15 => 'htm',
    16 => 'phtml',
    17 => 'phar',
  ),
  'upload_dir' => 'upload/',
  'upload_maxsize' => 30000000,
  'use_common_ml_dir' => false,
  'use_real_names' => true,
  'valid_image_ext' => 
  array (
    0 => 'gif',
    1 => 'png',
    2 => 'jpg',
    3 => 'jpeg',
    4 => 'svg',
    5 => 'bmp',
  ),
  'valid_imap_ports' => 
  array (
    0 => '110',
    1 => '143',
    2 => '993',
    3 => '995',
  ),
  'vcal_time' => '2',
  'verify_client_ip' => true,
  'web_to_lead_allowed_redirect_hosts' => 
  array (
  ),
);