<?php
/**
 * Script de rebuild de extensiones - alternativa segura
 */
if (!defined('sugarEntry')) { define('sugarEntry', true); }
chdir(__DIR__ . '/../public/legacy');
require_once('include/entryPoint.php');

// Simular admin
$GLOBALS['current_user'] = BeanFactory::newBean('Users');
$GLOBALS['current_user']->retrieve('1');
$GLOBALS['current_user']->is_admin = 1;

echo "Reconstruyendo extensiones...\n";

// Método 1: Usar SugarAutoLoader para rebuild
require_once('include/utils/sugar_file_utils.php');

// Reconstruir los archivos Ext de cada módulo manualmente
$module_dirs = glob('custom/Extension/modules/*', GLOB_ONLYDIR);
$rebuilt = 0;
foreach ($module_dirs as $mod_dir) {
    $mod_name = basename($mod_dir);
    $ext_types = ['Ext/Vardefs', 'Ext/Language', 'Ext/Layoutdefs', 'Ext/LogicHooks'];
    
    foreach ($ext_types as $ext_type) {
        $source_dir = $mod_dir . '/' . $ext_type;
        if (!is_dir($source_dir)) continue;
        
        // Determinar destino
        $type_name = basename($ext_type);
        $dest_dir = "custom/modules/$mod_name/Ext/" . $type_name;
        if (!is_dir($dest_dir)) {
            mkdir($dest_dir, 0755, true);
        }
        
        // Concatenar todos los archivos fuente en el archivo Ext
        $output_file = $dest_dir . '/' . strtolower($type_name) . '.ext.php';
        $content = "<?php\n// Auto-generated by rebuild - " . date('Y-m-d H:i:s') . "\n";
        
        $source_files = glob($source_dir . '/*.php');
        foreach ($source_files as $sf) {
            $file_content = file_get_contents($sf);
            // Remove opening PHP tags
            $file_content = preg_replace('/^<\?php\s*/i', '', $file_content);
            $content .= "\n// --- " . basename($sf) . " ---\n" . $file_content . "\n";
        }
        
        file_put_contents($output_file, $content);
        $rebuilt++;
        echo "  ✓ Rebuilt: $mod_name/$type_name\n";
    }
}

// Rebuild application extensions
$app_ext_dir = 'custom/Extension/application/Ext/Language';
if (is_dir($app_ext_dir)) {
    $dest_dir = 'custom/application/Ext/Language';
    if (!is_dir($dest_dir)) mkdir($dest_dir, 0755, true);
    
    $content = "<?php\n// Auto-generated " . date('Y-m-d H:i:s') . "\n";
    foreach (glob($app_ext_dir . '/*.php') as $sf) {
        $fc = file_get_contents($sf);
        $fc = preg_replace('/^<\?php\s*/i', '', $fc);
        $content .= "\n// --- " . basename($sf) . " ---\n" . $fc . "\n";
    }
    file_put_contents($dest_dir . '/language.ext.php', $content);
    echo "  ✓ Rebuilt: application/Language\n";
    $rebuilt++;
}

// Limpiar caché de vardefs y language
$cache_paths = [
    'cache/modules/Contacts/vardefs.php',
    'cache/modules/Leads/vardefs.php',
    'cache/modules/Contacts/metadata/detailviewdefs.php',
    'cache/modules/Contacts/metadata/listviewdefs.php',
    'cache/modules/Contacts/metadata/editviewdefs.php',
    'cache/modules/Leads/metadata/detailviewdefs.php',
    'cache/modules/Leads/metadata/listviewdefs.php',
    'cache/Unified_search_index.php',
    'cache/include/language/en_us.lang.php',
    'cache/include/language/es_ES.lang.php',
];

foreach ($cache_paths as $cp) {
    if (file_exists($cp)) {
        unlink($cp);
        echo "  ✓ Cache limpiado: $cp\n";
    }
}

echo "\nTotal rebuilt: $rebuilt\n";
echo "✅ Rebuild completado. Los cambios estarán activos al recargar SuiteCRM.\n";
